services:
  db:
    image: postgres:16-alpine
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '1213122'
      POSTGRES_DB: core_db
    ports:
      - "5432:5432"
    volumes:
      - nexus_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nexus_db: