
services:
  db:
    image: postgres:16-alpine
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '1213122'
      POSTGRES_DB: core_db
    ports:
      - "5432:5432"
    volumes:
      - nexus_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: nexus_keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: '1213122' # Defina sua senha do painel aqui
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: '1213122'
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  nexus_db: