name: 'Integração Anteriores'

jobs:
  uni:
    modo: 'prod'
    name: 'Pos Uni'
    sync:
      turmas: true
      matriculas:
        aluno: true
        professor: true
    unidade: 'UniEVANGÉLICA'
    curso-tipo: 'POS'