name: 'Integração 2026-1 SemiPresenciais'

jobs:

  unievangelica:
    modo: 'prod'
    name: 'Graduação SemiPresencial'
    sync:
      turmas: true 
      matriculas:
        aluno: true
        professor: true
    unidade: 'Ead_Unievangelica'
    curso-tipo: 'SUP'
    periodo: '2026-1'
    
    # categoria:
    #   - 'Graduação EaD'
    #   - '%PERIODO'

    # sala:
    #   - '%DISCIPLINA_NOME'
    #   - ' - '
    #   - '%TURMA_ID'

    # coursetemplate: