name: 'Integração Turmas Práticas 2026-1'

jobs:

  unievangelica:
    modo: 'prod'
    name: 'Turmas Práticas 2026-1'
    sync:
      turmas: true 
      matriculas:
        aluno: true
        professor: false
    unidade: 'UniEVANGÉLICA'
    curso-tipo: 'SUP'
    periodo: '2026-1'
    