default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: core_db
  host: 127.0.0.1
  port: 5433
  username: admin
  password: 1213122
test:
  <<: *default
  database: nexus_core_rails_test

production:
  <<: *default
